services:
  database-ai-db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database-ai
